<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="6.1.3" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PolyGear_DTO_SOF\PolyGear_DTO_SOF.csproj" />
    <ProjectReference Include="..\PolyGear_UTIL_SOF\PolyGear_UTIL_SOF.csproj" />
  </ItemGroup>

</Project>
