<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0-windows</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PolyGear_DTO_SOF\PolyGear_DTO_SOF.csproj" />
  </ItemGroup>
	
	<ItemGroup>
		<FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />
	</ItemGroup>
	
	<ItemGroup>
	  <Folder Include="Validation\" />
	</ItemGroup>

</Project>
