<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	  <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.13.0" />
    <PackageReference Include="MimeKit" Version="4.13.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PolyGear_BLL_SOF\PolyGear_BLL_SOF.csproj" />
    <ProjectReference Include="..\PolyGear_DTO_SOF\PolyGear_DTO_SOF.csproj" />
    <ProjectReference Include="..\PolyGear_UTIL_SOF\PolyGear_UTIL_SOF.csproj" />
  </ItemGroup>

</Project>